import Link from "next/link";
import "./globals.css";
import { Control } from "./Control";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const res = await fetch("http://localhost:9999/topics", {
    cache: "no-store",
  });
  const topics = await res.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">
            <img src="/vercel.svg" width={140}></img>
          </Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        <br />
        {children}
        <br />
        <Control />
      </body>
    </html>
  );
}
